### ISSUE TITLE
Problems with web server

### ISSUE THREAD

**Issue by c600g** [pacman-ghost/vasl-templates#1]
I am using the Docker build of vasl-templates, and when I load the vasl-templates web app (localhost:5010), the spinning "loading" symbol never goes away, and I am not able to switch to the non-active tabs (e.g. German OB, American OB, etc.)

I have mapped the vasl module file and extensions directory correctly, but do not have any chapter H notes files. The docker run command I am using is as follows:

```
docker run --rm -it --name vasl-templates -p 5010:5010 -v /home/alank/Games/vasl/vasl-6.4.3.vmod:/data/vasl.vmod -v /home/alank/Games/vasl/extensions:/data/vasl-extensions vasl-templates
```

**Comment by pacman-ghost** [comment]
If the spinner doesn't go away, that means the webapp had a problem during startup (the other tabs don't get activated until startup completes). Open up the console and see if any error messages were logged.

Also, depending on the host OS, there may also be SELinux permission problems - check the documentation on how to fix these.

**Comment by c600g** [comment]
I'm running Ubuntu 18.04, so no SELinux.

The console is giving me three errors:

 * scenario1.png - Failed to load resource: the server responded with a status of 404 (NOT FOUND)
 * :5010/vehicles/notes:1 - Failed to load resource: the server responded with a status of 404 (NOT FOUND)
 * :5010/ordnance/notes:1 - Failed to load resource: the server responded with a status of 404 (NOT FOUND)

Thanks much!

**Comment by c600g** [comment]
I seem to have it working now, if I map the /data/chapter-h-notes directory. I wasn't doing this previously, which may have caused the error.

**Comment by pacman-ghost** [comment]
No worries. There may well be an issue if the Chapter H directory hasn't been mapped - I'll look into it.
