### ISSUE TITLE
Mismatch between scenario date in datepicker and exported snippet text

### ISSUE THREAD

**Issue by mulcare** [pacman-ghost/vasl-templates#4]
After selecting a date in the datepicker, the resulting snippet export has the date off by one (a day earlier).

If timezone considerations might be relevant, I'm trying this around 2:00pm EDT (-4 UTC). I have not tried at other times.

**datepicker**:
![datepicker with selected date](https://s3.amazonaws.com/butt.es/vasl-templates_UbhUHhSD81.png)

**snippet export**:
`
...
<span class="small"> (10th January, 1940) </span>
...`

**Comment by pacman-ghost** [comment]
Sigh... What version are you running? This was an issue before (yes, it's timezones), but I thought I fixed it :-/

What happens if you save the scenario - is the date wrong in the JSON file, as well? When you load it back in?

**Comment by mulcare** [comment]
I'm using version `1.2`.

I did save the scenario earlier; here's the JSON contents:

`
{
  "SCENARIO_NAME": "Torment at Tormua",
  "SCENARIO_ID": "164",
  "SCENARIO_LOCATION": "Tormua, Finland",
  "SCENARIO_DATE": "1940-01-11",
  "SCENARIO_WIDTH": "350",
  "ROAR_ID": "5002",
  "VICTORY_CONDITIONS_WIDTH": "300px",
  "SSR_WIDTH": "300px",
  "OB_VEHICLES_WIDTH_1": "",
  "OB_VEHICLES_MA_NOTES_WIDTH_1": "300px",
  "OB_ORDNANCE_WIDTH_1": "",
  "OB_ORDNANCE_MA_NOTES_WIDTH_1": "300px",
  "OB_VEHICLES_WIDTH_2": "",
  "OB_VEHICLES_MA_NOTES_WIDTH_2": "300px",
  "OB_ORDNANCE_WIDTH_2": "",
  "OB_ORDNANCE_MA_NOTES_WIDTH_2": "300px",
  "VICTORY_CONDITIONS": "The Finns win at game end by amassing more VP than the Russians. CVP are awarded normally <i>[EXC: vehicle crews do not count; prisoners do not count double]</i>, and each building Controlled on board 42 is worth 2 VP.",
  "SCENARIO_THEATER": "ETO",
  "PLAYER_1": "russian",
  "PLAYER_1_ELR": "3",
  "PLAYER_1_SAN": "3",
  "PLAYER_2": "finnish",
  "PLAYER_2_ELR": "4",
  "PLAYER_2_SAN": "3",
  "SSR": [
    "E1.16 applies to Foxholes, provdied a hidden unit(s) is set up beneath them. Finnish Elite/1st-Line Personnel have MOL (A22.6) capability, but may only make MOL Check drs vs AFV.",
    "Both sides have Winter Camoflage (E3.712).",
    "Commissar exchange (A25.22) is NA. AFV crews may not voluntarily Abandon (D5.4) their vehicles."
  ],
  "OB_VEHICLES_1": [
    {
      "id": "ru/v:007",
      "seq_id": 1,
      "name": "T-26 M33",
      "image_id": "555/0"
    }
  ],
  "OB_ORDNANCE_2": [
    {
      "id": "fi/o:011",
      "seq_id": 1,
      "name": "45 PstK/32(r)"
    }
  ],
  "SCENARIO_NOTES": [],
  "OB_SETUPS_1": [],
  "OB_SETUPS_2": [],
  "OB_NOTES_1": [],
  "OB_NOTES_2": [],
  "_app_version": "v1.2",
  "_last_update_time": "2020-10-21T19:37:14.826Z",
  "_creation_time": "2020-10-21T19:37:14.826Z"
}
`

**Comment by pacman-ghost** [comment]
OK, thanks, I'll take a look it.

I hates Javascript :-/

**Comment by pacman-ghost** [comment]
OK, I've found the problem and added a fix.

The next version (v1.3) will be released in a few weeks. It's already been tagged and built, and so I don't want to touch that. So, there will be a v1.3a, with this fix in it - would you like to take it for a spin? All it means is that you will be upgrading to v1.3 a bit earlier than everyone else :-)

**Comment by mulcare** [comment]
Would be happy to try it out and report back! Appreciate all your work on these ASL tools--they are great.

**Comment by pacman-ghost** [comment]
Give this a go: https://vasl-templates.org/tmp/v13a-prerelease.zip

**Comment by mulcare** [comment]
Imported the json scenario file and the snippet exports correctly now. Thank you! Looking forward to poking around and seeing the new additions, too.
